apiVersion: v1
kind: PersistentVolume
metadata:
  name: vrising-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.172
    path: /mnt/datastore/tank-general/minecraft/v-rising
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs   # <-- add this
