apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrising-pvc
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs  # MUST match PV exactly
