apiVersion: v1
kind: Namespace
metadata:
  name: personal-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-portfolio
  namespace: personal-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-portfolio
  template:
    metadata:
      labels:
        app: react-portfolio
    spec:
      containers:
        - name: react-portfolio
          image: harbor.local/portfolio/react-portfolio:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-portfolio-service
  namespace: personal-apps
spec:
  selector:
    app: react-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-portfolio-ingress
  namespace: personal-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: portfolio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-portfolio-service
                port:
                  number: 80

