apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-grafana-prometheus-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/datastore/tank-general/minecraft/grafana-data
    server: 192.168.50.172
