# minecraft-server1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server1
  template:
    metadata:
      labels:
        app: minecraft-server1
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: "8G"
            - name: TYPE
              value: "PAPER"
            - name: MOTD
              value: |
                A §l§cTardi§r Minecraft §nserver
                Running on %VERSION%
                
            - name: OPS
              value: |
               Eccentric87
            - name: PLUGINS
              value: |
                 https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
                 https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
          ports:
            - containerPort: 25565
            - containerPort: 19132
              protocol: UDP
          volumeMounts:
            - name: mc-data
              mountPath: /data
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: minecraft-server1-pvc

