# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-server1-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  nfs:
    path: /mnt/datastore/tank-general/minecraft/server1
    server: 192.168.50.172

